### ISSUE TITLE
Function.flip should supporting flipping curried functions

### ISSUE THREAD

**Issue by jasonkuhrt** [Effect-TS/core#1123]
**Is your feature request related to a problem? Please describe.**

`flip` from `@effect-ts/core/Function` should preserve the currying nature of the Effect-TS API.

**Describe the solution you'd like**
If TS can express a `flip` that would be able to accurately flip both curried and non-curried functions then great.

If not, and thus we need a separation between a `flip` for curried and a `flip` for non-curried, then, I suggest that `flip` be the curried one and another new `flip` be introduced like `flipUncurried` or `flipNoCurry`.

Given Effect-TS is curried by default in its APIs, the `flip` it ships with should respect and be consistent with that, I think.

**Describe alternatives you've considered**
None

**Additional context**
https://discord.com/channels/795981131316985866/795983589644304396/949779407025872896

**Comment by mikearnaldi** [comment]
The new effect release will be based on the new version of fp-ts that solved this already https://github.com/fp-ts/data/blob/main/src/Function.ts#L165

**Comment by mikearnaldi** [comment]
Probably on the effect's discord in the `fp-ts` channel, summarized when Giulio started working on the new version of fp-ts he tried the HKT encoding that we figured out for effect (described at https://dev.to/matechs/encoding-of-hkts-in-typescript-5c3) that can handle variance of parameters and that makes overloads not needed and decided to give it a serious try, then we privately discussed for a bit and came to the conclusion that it would be better for the ecosystem if instead of having two projects with partially overlapping scope we would have one cohesive and cooperating ecosystem where each project is focused on a specific problem so we came out with the current idea being:

- `@fp-ts/core` that focuses on TypeClasses and HKT abstractions
- `@fp-ts/data` that focuses on common Data Structures such as Either, Option, Array, HashMap, SafeEval, etc
- `@fp-ts/codec` that focuses on domain modelling and serialization
- `@fp-ts/optic` that focuses on abstract data manipulation
- `@effect/io` that focuses on effect modelling with modules such as Effect, Layer, Queue, etc
- `@effect/stm` that focuses on transactional data structures
- `@effect/stream` that focuses on streaming data structures
- `@effect/query` that focuses on query planning and optimization
- `@effect/*` individual integrations such as node, express, fastify, etc.

Generally the `@effect/*` org will focus on higher-level abstractions where instead `@fp-ts/*` will focus on lower-level abstractions.

You can follow progress on repos too:

- https://github.com/fp-ts/core
- https://github.com/fp-ts/data
- https://github.com/effect/io

I should add that while this is good for library development it may turn into a bit of a mess for a user who's objective is just to learn and use the ecosystem for that we are thinking about a single `effect` package that re-exports parts of the ecosystem as a prelude package, you can follow that discussion at https://github.com/Effect-TS/core/issues/1311
