### ISSUE TITLE
@matechs/node extensions wishlist

### ISSUE THREAD

**Issue by patroza** [Effect-TS/core#271]
There's been talk about a NodeJS library for @matechs.
Using this issue to document some feature ideas:

## Ideas
- [ ] File streams; reading and writing streams like in ZIO streams. ZStream.fromFile https://youtu.be/OiuKbpMOKsc 18:50
- [ ] `S.fromObjectReadStream` mentioned in Slack.

**Comment by qlonik** [comment]
It would be nice to see fs methods wrapped into effects

**Comment by mikearnaldi** [comment]
@qlonik stream based fs methods? can you produce a list of the ones you think are a fit?

**Comment by qlonik** [comment]
Sorry, I misunderstood that we were talking about stream based fs methods only. For things like move/copy/delete/writeFile/readFile I'm not sure that stream based api is needed. I was thinking that even providing sync/async effect wrappers would be nice. Since `effectify` doesn't handle overloads very well, and often manual wrappers need to be written.

But about stream based fs wrappers, I agree that in some cases it would be convenient to have stream based api. For example there is a handful of functions which either return or accept Node Streams, so those could probably be a good candidate to try how can we implement the support. Things like `createReadStream` and `createWriteStream`. There are also methods which return Buffer, which could potentially be a stream of buffer chunks (I dont know zio, but it seems like this is similar to their fs streams? Correct me if I'm wrong here).

What do you think @patroza ?

**Comment by mikearnaldi** [comment]
Well actually the node extension could be both effect & stream, the idea was initially stream to bring back some of the utils but it would make sense having more

**Comment by qlonik** [comment]
I had another idea: node.js has worker_threads module available, so it would be interesting to see if it is possible to provide driver which only works in node and can use those threads.

**Comment by mikearnaldi** [comment]
@qlonik worker_threads are still separated processes and use different memory segments, it is impossible to leverage those for a driver.

To update on this, I am holding off from the streams based node interop because the encoding of streams will change slightly, at the moment we are not allowing any form of batching at the source and this makes streams not extremely performant in tasks like reading chunked files.

When next version will be ready I will port over the encoding used in ZIO that allows for that

**Comment by patroza** [comment]
> Sorry, I misunderstood that we were talking about stream based fs methods only. For things like move/copy/delete/writeFile/readFile I'm not sure that stream based api is needed. I was thinking that even providing sync/async effect wrappers would be nice. Since `effectify` doesn't handle overloads very well, and often manual wrappers need to be written.
> 
> But about stream based fs wrappers, I agree that in some cases it would be convenient to have stream based api. For example there is a handful of functions which either return or accept Node Streams, so those could probably be a good candidate to try how can we implement the support. Things like `createReadStream` and `createWriteStream`. There are also methods which return Buffer, which could potentially be a stream of buffer chunks (I dont know zio, but it seems like this is similar to their fs streams? Correct me if I'm wrong here).
> 
> What do you think @patroza ?

I’m totally for Effect and maybe even Sync wrappers. I keep repeating them over and over in my projects. Maybe good we start somewhere and extend as we find more usages?
