### ISSUE TITLE
Naming for `@effect-ts/prelude`

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/core#580]
With the advent of webpack 5 namespace re-exports are now tree-shakable and we could introduce a `@effect-ts/prelude` package that re-export modules from the ecosystem core packages (i.e. core, monocle, morphic) let's discuss on the names of those re-exports.

I don't have strong preferences buy:
1) Full-names are terrible and long `import {Effect} from "@effect-ts/prelude"` because usage becomes verbose `Effect.chain` etc
2) Short-names are conflicted, for example is `E` Exit or Either

**Comment by patroza** [comment]
Export long names, let people alias alternative names (like short names) on their own.

Especially considering with current import * as, you can use a short alias but still see a long name in the path.

**Comment by schickling** [comment]
Given that the `@effect-ts/core` module itself currently doesn't export anything, it could be great to do theses exports on that level (similar to how Lodash works). This way a user doesn't have to install an additional package.

**Comment by mikearnaldi** [comment]
The idea of having a separated module is to also include packages from ecosystem libraries like morphic but I guess they are not mutually exclusive

**Comment by mikearnaldi** [comment]
https://github.com/Effect-TS/core/pull/583

It is really horrible to use and if the purpose is to re-alias like:

```ts
import { Effect as T } from "@effect-ts/core"
```

then I don't understand the point in the first place

**Comment by patroza** [comment]
The way how I used to use it was to re export all effect ts modules from a single place in one of my own libraries and then if I wanted to extend a module, I would create an extended version and then in my index replace the original module with my own.

In the meantime I got used to using the import * syntax instead, and just update the paths to my own extended module if the need arises.

Why I think it’s important to have full names available, even to alias it on the spot, provided either by path or by export name is that it provides a lookup table at the top of each file, to help the uninitiated, or to help remind the veterans :)

With the root export of all now, users have the option to go for full name import, or with as alias, or * as with full path, as they desire.

**Comment by mikearnaldi** [comment]
Reason for closing:
exports are in core/index already and feedback is: nobody is using it.

I will keep them in core for now, not guaranteed to stay unless there is a significant benefit presented with sustained usage

**Comment by jasonkuhrt** [comment]
I propose gradual tiers of adoption

1. toolkit module namespace (or default)
2. Tool Module Namespaces
3. Tool Module Namespaces Abbreviated 

### (1) Toolkit Namespace

This can be achieved in one of two ways. A default export or an internal namespace. IIUC we want internal namespace because default export requires building a runtime object and does not work with treeshaking. But for completeness sake here it is:

#### _default export_

```ts
$ // autoimport kicks in
```
```ts
import $ from '@effect-ts/prelude`

$.<tab> // access to EVERYTHING
$.Effect
$.Option
$.Either
// ...
```

The const that ETS defines internally and exports as default will be what the auto-import system picks up on. So for example if internally ETS does `export default const $ = ...` then anywhere in the codebase users can type just three characters:



Now namespace...

#### _module namespace export_

```ts
$ // autoimport kicks in
```
```ts
import { $ } from '@effect-ts/prelude'

$.<tab> // access to EVERYTHING
$.Effect
$.Option
$.Either
// ...
```


#### Identifier Naming

Why `$`? It is just a convention. We want something distinct and easy to use. At the same time if this usage is designed as the first step in the ramp toward API internalization than we know that its not the primary use-case and just training wheels. So consideration for an ident that isn't useful in other places is also there. Ideas:

```
$
_
$$

ets
$ets
$$ets

ETS
$ETS
$$ETS

EFF
eff
$eff
$EFF
```

#### Tool Module Namespaces

After a while, accessing the API through a single identifier might feel verbose if for no other reason than the extra namespace one has to type through. Instead of `$.Effect.<...>` users may begin to just prefer typing `Effect.<...>`


```ts
Effect // autoimport kicks in
```
```ts
import { Effect } from '@effect-ts/prelude'

Effect. // access to EVERYTHING inside Effect
Effect.gen
Effect.map
Effect.filter
// ...
```

#### Tool Module Namespaces Abbreviated

After a while yet more succinctness may become desirable to experiences users. So singler letter namespaces can be designed. All of these namespaces should be single letters, unless we overflow into 25+ then allow 2. The most common namespaces should be given priority to letters. Lesser used should be given access to unused letters that match their earlier character in their name. Also other conventions can be applied if we know better for certain cases. For example `E` is for Either while `T` is for `Effect`.

```ts
E // autoimport kicks in
```
```ts
import { E } from '@effect-ts/prelude/abbreviations'

E. // access to EVERYTHING inside Effect
E.gen
E.map
E.filter
// ...
```

I think these should come from a sub module so that confusing overlap is avoided. As a user, I want to see one set of the API, not overlapping API sets, e.g. I never want to see the abbreviations and the non-abbrevaitions in the same autocomplete space (autocomplete in `import {...} from "@effect-ts/prelude"`

## Areas for further improvement

I see two things that could significantly improve ergonomics here.

1. Package name of `effect-ts`. The `@effect-ts` packages are confusing because they range in use-case in the hierarchy. The non-scoped privileged package is the perfect entrypoint for consumers, especially newcomers.


```ts
import { Effect } from 'effect-ts'

Effect. // access to EVERYTHING inside Effect
Effect.gen
Effect.map
Effect.filter
// ...
```

2. Once https://github.com/microsoft/TypeScript/issues/36792 lands <3 <3 <3 then effect-ts can be changed to merge types with module namespaces as is possible with TS namespaces but unlike them WITHOUT LOSING TREE SHAKING SUPPORT <3 


```ts
Either //autoimport
```

```ts
import { Either } from 'effect-ts'

// use in type position
const foo = (bar: Either) => /* ... */

// access ADT members in type position
const foo = (bar: Either.Left) => /* ... */


// access API members in type position
const foo = pipe(Either.fromOption, /* ... */)
```

Of course this would apply for the abbreviations too:

```ts
Either //autoimport
```

```ts
import { E } from 'effect-ts/abbreviations'

// use in type position
const foo = (bar: E) => /* ... */

// access ADT members in type position
const foo = (bar: E.Left) => /* ... */

// access API members in type position
const foo = pipe(E.fromOption, /* ... */)
```

**Comment by mikearnaldi** [comment]
Reopening given recent activity

**Comment by jasonkuhrt** [comment]
The `$` stuff is probably not practical and mostly for discovering the API without losing the current flow. As such maybe there is an alternative solution for this use-case of discovery. But I'm not sure...

**Comment by jasonkuhrt** [comment]
Does the effect ts community want a package that includes EVERYTHING? Not just core but also `@effect-ts/query` etc.?

**Comment by mikearnaldi** [comment]
> Does the effect ts community want a package that includes EVERYTHING? Not just core but also `@effect-ts/query` etc.?
> 
> Reason I ask is maybe this shouldn't be prelude (which signals base) but some other name that then takes on exporting all that stuff.
> 
> Thanks to tree shaking it seems viabale.
> 
> I guess one downside is that the version of such a package would be changing maybe very often.

I think this could be a good idea, we could take `effect-ts` for that (in the meanwhile I took ownership of the npm package `https://www.npmjs.com/package/effect-ts`) and if properly structure it could form a good basis for an "always consistent" ecosystem release.

Tree shaking has improved with WP5 so we could use namespace exports `export * as X` or similar but I think that we would still need to provide alternatives for example `import { Query } from "effect-ts"` and `import * as Query from "effect-ts/query"` and ``import { Request } from "effect-ts/query"`` and `import * as Request from "effect-ts/query/request"`

**Comment by patroza** [comment]
@mikearnaldi personally hate all the naming collisions, I try very hard to hide them in import auto complete for instance, by pushing as much external dependencies to some other package, from there export the things I want, and then use this package as dependency for all other, so that my import sanity remains.
Otherwise an `Effect` import from 5 different places is just annoying, and especially for new people real DH (devhell).

**Comment by mikearnaldi** [comment]
@patroza seems mostly intellij having fun, how would you propose to structure system & core in a way where no re-export are needed?
