### ISSUE TITLE
Provide way to get index in T.forEach (...) functions

### ISSUE THREAD

**Issue by schickling** [Effect-TS/core#961]
Currently there's no way to get the current index in `T.forEach`, `T.forEachPar` etc.

Note sure if possible but ideally this could be done with a function overload and therefor avoiding a duplication of the related exports.

**Comment by adrian-gierakowski** [comment]
How about a solution similar to https://ramdajs.com/docs/#addIndex?

**Comment by mikearnaldi** [comment]
Not sure there is a valid typing for an addIndex, doing it via function overload isn't advisable because you could pass to forEach a function with an optional second argument (like succeed, fail, or anything that has tracing) and there is no way of distinguishing at runtime if the function you pass in wants an index or not.

The easiest would be to add `T.forEachWithIndex` and similar variants, or maybe think of returning extended functions and like from forEach return a function with a `.indexed` method like `T.forEach.indexed(() => ` even though that could have perf implication in constructing the forEach

**Comment by wesselvdv** [comment]
I'd say this can be closed no? With #968 being merged?
